language: node_js

node_js:
- 9.2.1

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'CREATE DATABASE "maco_bot_test";' -U postgres
  - NODE_ENV=test knex migrate:latest

env:
  - TEST_DIR=./
  - TEST_DIR=./client

script: cd $TEST_DIR && npm install && jest --runInBand
