export const LOAD_CLIENTS_STARTED = 'client-list/LOAD_CLIENTS_STARTED'
export const LOAD_CLIENTS_SUCCEEDED = 'client-list/LOAD_CLIENTS_SUCCEEDED'
export const CHANGE_NEW_CLIENT = 'client-list/CHANGE_NEW_CLIENT'
export const ADD_CLIENT_STARTED = 'client-list/ADD_CLIENT_STARTED'
export const ADD_CLIENT_SUCCEEDED = 'client-list/ADD_CLIENT_SUCCEEDED'
