export const LOAD_PRODUCT_STARTED = 'product-details/LOAD_PRODUCT_STARTED'
export const LOAD_PRODUCT_SUCCEEDED = 'product-details/LOAD_PRODUCT_SUCCEEDED'
export const EDIT_PRODUCT = 'product-details/EDIT_PRODUCT'
export const UPDATE_PRODUCT_STARTED = 'product-details/UPDATE_PRODUCT_STARTED'
export const UPDATE_PRODUCT_SUCCEEDED = 'product-details/UPDATE_PRODUCT_SUCCEEDED'
export const CANCEL_EDIT_PRODUCT = 'product-details/CANCEL_EDIT_PRODUCT'
export const REMOVE_PRODUCT_STARTED = 'product-details/REMOVE_PRODUCT_STARTED'
export const REMOVE_PRODUCT_SUCCEEDED = 'product-details/REMOVE_PRODUCT_SUCCEEDED'
