export const HANDLE_AUTH_CALLBACK = 'routing/HANDLE_AUTH_CALLBACK'
export const GO_TO_HOME = 'routing/GO_TO_HOME'
export const GO_TO_CLIENTS_LIST = 'routing/GO_TO_CLIENTS_LIST'
export const GO_TO_CLIENT_DETAILS = 'routing/GO_TO_CLIENT_DETAILS'
export const GO_TO_PRODUCT_DETAILS = 'routing/GO_TO_PRODUCT_DETAILS'
export const GO_TO_EQUIPMENT_LIST = 'routing/GO_TO_EQUIPMENT_LIST'
export const GO_TO_APIS_LIST = 'routing/GO_TO_APIS_LIST'
